# Generated by Django 4.0.3 on 2022-03-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='static/image')),
            ],
        ),
    ]
