# Generated by Django 4.0.3 on 2022-03-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articalid', models.IntegerField(verbose_name='文章id')),
                ('user', models.CharField(max_length=30, verbose_name='ls评论人')),
                ('content', models.CharField(max_length=100, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
        ),
    ]
